// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v2.7.0 with parameter "target=js,js_import_style=legacy_commonjs"
// @generated from file helloworld.proto (package helloworld, syntax proto3)
/* eslint-disable */

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

const { fileDesc, messageDesc, serviceDesc } = require("@bufbuild/protobuf/codegenv2");

/**
 * Describes the file helloworld.proto.
 */
const file_helloworld = /*@__PURE__*/
  fileDesc("ChBoZWxsb3dvcmxkLnByb3RvEgpoZWxsb3dvcmxkIhwKDEhlbGxvUmVxdWVzdBIMCgRuYW1lGAEgASgJIh0KCkhlbGxvUmVwbHkSDwoHbWVzc2FnZRgBIAEoCTKWAQoHR3JlZXRlchI+CghTYXlIZWxsbxIYLmhlbGxvd29ybGQuSGVsbG9SZXF1ZXN0GhYuaGVsbG93b3JsZC5IZWxsb1JlcGx5IgASSwoTU2F5SGVsbG9TdHJlYW1SZXBseRIYLmhlbGxvd29ybGQuSGVsbG9SZXF1ZXN0GhYuaGVsbG93b3JsZC5IZWxsb1JlcGx5IgAwAUI2Chtpby5ncnBjLmV4YW1wbGVzLmhlbGxvd29ybGRCD0hlbGxvV29ybGRQcm90b1ABogIDSExXYgZwcm90bzM");

/**
 * Describes the message helloworld.HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
const HelloRequestSchema = /*@__PURE__*/
  messageDesc(file_helloworld, 0);

/**
 * Describes the message helloworld.HelloReply.
 * Use `create(HelloReplySchema)` to create a new message.
 */
const HelloReplySchema = /*@__PURE__*/
  messageDesc(file_helloworld, 1);

/**
 * The greeting service definition.
 *
 * @generated from service helloworld.Greeter
 */
const Greeter = /*@__PURE__*/
  serviceDesc(file_helloworld, 0);


exports.file_helloworld = file_helloworld;
exports.HelloRequestSchema = HelloRequestSchema;
exports.HelloReplySchema = HelloReplySchema;
exports.Greeter = Greeter;
